/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.41.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { GameAbi } from './GameAbi';

export { GameAbi__factory } from './factories/GameAbi__factory';
